server:
  port: 8080

management:
  server:
    port: 8080
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,info,prometheus,liveness,readiness,circuitbreakers,circuitbreakerevents
  endpoint:
    health:
      show-details: always
  health:
    probes:
      enabled: true

logging:
  config: classpath:logback.xml

spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_DATES_WITH_ZONE_ID: true
  config:
    import:
      - aws-parameterstore:/config/patient-api_prod/

system:
  id-service: patient-api
  collection:
    patient: Patient
